baseURL = "https://runink.org/"
title = "Runink"
theme = "docsy"
languageCode = "en-us"
enableRobotsTXT = true

[params]
  copyright = "Runink"
  github_repo = "https://github.com/paesdan/runink"
  # Site Branding
  theme_variant = "custom"  # Important to trigger custom styling

  [params.style]
    primary = "#98FB98" # Light Green (PaleGreen)
    secondary = "#D8BFD8" # Light Purple (Thistle)
    accent = "#FFDAB9" # Light Orange (Peach Puff)
    font = "Roboto"
    font_secondary = "Open Sans"

    [params.assets]
    customCSS = ["css/custom.css"]


[markup]
  [markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  identifier = "docs"
  name = "Docs"
  url = "/docs/"
  weight = 10

[[menu.main]]
  identifier = "forum"
  name = "Forum"
  url = "/forum/"
  weight = 20

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 30

[module]
  [[module.imports]]
    path = "github.com/FortAwesome/Font-Awesome"
    disable = true